### ISSUE TITLE
How do I add to my project

### ISSUE THREAD

**Issue by OFriedle** [qwe321qwe321qwe321/Unity-DiscordWebhook#1]
Hi, I have not added a package to a unity project when not in the unity package file type before and I can't seem to find how to do it. I'm a bit confused and would really appreciate some help thanks.

**Comment by qwe321qwe321qwe321** [comment]
Hello, you can do so using the **Package Manager** with a Git URL. Here’s how:

1. **Open the Package Manager** in Unity (`Window` > `Package Manager`).
2. Click on the `+` button at the top-left corner of the window.
3. Select `Add package from git URL...`.
4. Paste the following URL and click `Add`.
```
https://github.com/qwe321qwe321qwe321/Unity-DiscordWebhook.git?path=src/DiscordWebhook/Assets/DiscordWebhook
```
